### ISSUE TITLE
Configuração do ambiente de desenvolvimento

### ISSUE THREAD

**Issue by lilian-lilian** [lilian-lilian/GPTI_Agil#13]

**Comment by willxvi** [comment]
Tamanho previsto: 1
Tempo: 30 min

Eu como usuário do site;
Quero ter um ambiente configurável para desenvolvimento;
E que consiga adicionar e remover exercicios e atividades facilmente;
Assim poderei ser produtivo e entregar o site com qualidade e mais rápido.

**Comment by willxvi** [comment]
A configuração foi realizada na página utilizando o google sites.
