### ISSUE TITLE
Página com detalhes sobre os papeis no Scrum (Conceitos básicos)

### ISSUE THREAD

**Issue by lilian-lilian** [lilian-lilian/GPTI_Agil#17]

**Comment by willxvi** [comment]
Tamanho previsto: 2
Tempo: 30 min

Como um estudante;
Quero acessar um pagina onde posso encontrar informações sobre os papeis do scrum;
E poder acessar de forma interativa as informações;
Assim terei mais conhecimento sobre o tema para escolher em qual papel quero aprofundar meu estudo.

**Comment by willxvi** [comment]
Tamanho previsto: 5
Tempo: 1 hora
