### ISSUE TITLE
Página leitura de conhecimento de Scrum com Kaban (Scrum+ kanban)

### ISSUE THREAD

**Issue by willxvi** [lilian-lilian/GPTI_Agil#40]
Tamanho: 2
Tempo de execução: 30 minutos

Eu como estudante;
Quero ter acessso as informações de local, valores e como realizar a prova de certificação scrum;
Assim terei acesso a todas as informações para realizar a minha prova

**Comment by lilian-lilian** [comment]
https://www.scrum.org/resources/blog/15-dicas-para-tirar-certificacao-professional-scrum-master-psm-1
