### ISSUE TITLE
Links com simulados para certificação scrum (Certificação)

### ISSUE THREAD

**Issue by willxvi** [lilian-lilian/GPTI_Agil#50]
Como um estudante;
Quero acessar um pagina onde posso acessar links com simulados de certificação do scrum;
E poder realizar de forma interativa;
Assim poderei avaliar meu nivel de conhecimento do framework e avaliar em qual área preciso aprofundar meus estudos

**Comment by willxvi** [comment]
Tamanho previsto: 2
Tempo: 30 mim

**Comment by lilian-lilian** [comment]
https://www.gp4us.com.br/simulado-certificacao-scrummaster-1/

https://k21.global/simulado-de-scrum-para-a-prova-de-certificacao-da-scrum-alliance-certified-scrummaster

https://canalvalor.com/simulado-psm-i-gratuito-de-10-questoes-da-scrum-org/

https://conteudo.massimus.com/simulado-gratuito-de-scrum-master
